# Generated by Django 5.0.2 on 2024-11-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='desired_experience',
        ),
        migrations.AddField(
            model_name='internship',
            name='required_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
