# Generated by Django 5.0.2 on 2024-11-14 04:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='application',
            name='application_letter',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='application_letter'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Offer Extended', 'Offer Extended'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
