# Generated by Django 5.1.1 on 2024-10-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
