# Generated by Django 5.0.2 on 2024-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='desired_experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_skills',
            field=models.TextField(help_text='Comma-separated skills', null=True),
        ),
    ]
