# Generated by Django 5.0.2 on 2024-11-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_remove_internship_desired_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(blank=True, choices=[('arts_humanities', 'College of Arts and Humanities'), ('business_accountancy', 'College of Business and Accountancy'), ('criminal_justice', 'College of Criminal Justice Education'), ('engineering_technology', 'College of Engineering, Architecture, and Technology'), ('hospitality_tourism', 'College of Hospitality Management and Tourism'), ('nursing_health_sciences', 'College of Nursing and Health Sciences'), ('sciences', 'College of Sciences'), ('teacher_education', 'College of Teacher Education')], max_length=255, null=True),
        ),
    ]
