# Generated by Django 5.1.1 on 2024-10-15 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_remove_internship_student_internship_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='internship',
            name='requirements',
            field=models.TextField(default='Basic requirements include enthusiasm and a willingness to learn.'),
        ),
    ]
