# Generated by Django 5.1.1 on 2024-10-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
