# Generated by Django 5.0.2 on 2024-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_customuser_experience_customuser_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
