# Generated by Django 5.1.1 on 2024-09-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_customuser_reset_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_confirmed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
