# Generated by Django 5.0.2 on 2024-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_alter_internship_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
