# Generated by Django 5.0.2 on 2024-11-20 02:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_alter_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
