# Generated by Django 5.0.2 on 2024-11-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_internship_preferred_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='preferred_college',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='preferred_course',
        ),
    ]
