# Generated by Django 5.0.2 on 2024-11-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_organizationintern'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationintern',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organizationintern',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
