# Generated by Django 5.0.2 on 2024-12-01 13:25

import IMS.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_internship_preferred_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[IMS.models.validate_image_extension], verbose_name='image'),
        ),
    ]
