# Generated by Django 5.1.1 on 2024-10-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0008_remove_internship_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='max_applicants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
