# Generated by Django 5.0.2 on 2024-11-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0008_organizationintern_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationintern',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.internship'),
        ),
    ]
