# Generated by Django 5.1.1 on 2024-10-26 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0010_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_name',
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
