# Generated by Django 5.0.2 on 2024-12-01 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0010_alter_application_application_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_letter',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
