# Generated by Django 5.1.1 on 2024-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0011_remove_application_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_college',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student_course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
