# Generated by Django 5.1.1 on 2024-10-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0012_application_student_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('In Review', 'In Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Offer Extended', 'Offer Extended'), ('Completed', 'Completed')], default='Applied', max_length=50),
        ),
    ]
